# allowed types
failed_entry_columns = [
    "Bank Statement Date",
    "Bank Transaction ID",
    "Bank Reference Number",
    "Bank Description",
    "Bank Receipt",
    "Bank Disbursement",
    "CSGP Transaction Date",
    "CSGP Reference",
    "CSGP Module",
    "CSGP Description",
    "CSGP Receipt",
    "CSGP Disbursement",
    "Amount Difference",
    "Date Difference",
    "Reason",
    "Confidence",
    "Match Type",
    "Bank_UID",
    "CSGP_UID",
]
